services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB}
    ports:
      - '5432:5432'
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
